In [1]:
import numpy as np

In [4]:
intIndex = np.arange(0, 48)

In [13]:
intStride = 1
first = np.random.randint(1, high=20, size=(1, 256, 8, 6)).astype(np.float32)
rbot0 = np.zeros([first.shape[0], first.shape[2] + (6 * intStride), first.shape[3] + (6 * intStride), first.shape[1]], dtype=np.float32)

In [14]:
n = first.shape[2] * first.shape[3]

In [18]:
_input = first.reshape((256*8*6,))
output = rbot0.reshape((256*14*12,))

In [19]:
intPaddedY = (intIndex // 6) + 3*1;
intPaddedY

array([ 3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,
        5,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,
        8,  8,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10])

In [20]:
intPaddedX = (intIndex % 6) + 3*1;
intPaddedX

array([3, 4, 5, 6, 7, 8, 3, 4, 5, 6, 7, 8, 3, 4, 5, 6, 7, 8, 3, 4, 5, 6,
       7, 8, 3, 4, 5, 6, 7, 8, 3, 4, 5, 6, 7, 8, 3, 4, 5, 6, 7, 8, 3, 4,
       5, 6, 7, 8])

In [21]:
intRearrange = ((6 + 6*1) * intPaddedY) + intPaddedX;
intRearrange

array([ 39,  40,  41,  42,  43,  44,  51,  52,  53,  54,  55,  56,  63,
        64,  65,  66,  67,  68,  75,  76,  77,  78,  79,  80,  87,  88,
        89,  90,  91,  92,  99, 100, 101, 102, 103, 104, 111, 112, 113,
       114, 115, 116, 123, 124, 125, 126, 127, 128])

In [22]:
i = 0

for intSample in range(1):
    for intChannel in range(256):
        for int_rearrange in intRearrange:
            outIdx = (((intSample * 14 * 12) + int_rearrange) * 256) + intChannel;
            fltValue = _input[i]
            i += 1
            output[outIdx] = fltValue
            

In [24]:
_input

array([12.,  2., 11., ...,  6., 10.,  1.], dtype=float32)